ALTER TABLE Team DROP CONSTRAINT team_coach_id_fkey;

ALTER TABLE Team ADD CONSTRAINT team_coach_id_fkey
FOREIGN KEY (coach_id)
REFERENCES coach (id)
ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE Team
ALTER COLUMN coach_id DROP NOT NULL;